#!/usr/bin/env python3
"""Regenerate tools/snapshot_font.h from Pillow's bundled default font.

Only used to produce layout snapshots on the host. The 3DS draws with the
system font, so snapshots approximate glyph shapes and widths.
"""
from PIL import Image, ImageDraw, ImageFont

SIZE = 24  # matches the 3DS system font line height at text scale 1.0 (about 30px cell)
font = ImageFont.load_default(SIZE)
asc, desc = font.getmetrics()
lines = []
glyphs = []
for code in range(32, 127):
    ch = chr(code)
    adv = round(font.getlength(ch))
    img = Image.new("L", (SIZE * 2, SIZE * 2), 0)
    ImageDraw.Draw(img).text((SIZE // 2, 0), ch, font=font, fill=255)
    bbox = img.getbbox()
    if bbox is None:
        glyphs.append((adv, 0, 0, 0, 0, b""))
        continue
    x0, y0, x1, y1 = bbox
    crop = img.crop(bbox)
    glyphs.append((adv, x0 - SIZE // 2, y0, x1 - x0, y1 - y0, crop.tobytes()))

out = ["/* Generated by tools/gen_font.py. Do not edit. */",
       "#ifndef SNAPSHOT_FONT_H", "#define SNAPSHOT_FONT_H", "",
       "#include <stdint.h>", "",
       f"#define SNAPSHOT_FONT_SIZE {SIZE}",
       f"#define SNAPSHOT_FONT_ASCENT {asc}", "",
       "typedef struct { uint8_t advance; int8_t x; int8_t y; uint8_t w; uint8_t h; uint16_t offset; } snapshot_glyph;", ""]
data = bytearray()
rows = []
for adv, x, y, w, h, px in glyphs:
    rows.append(f"    {{{adv}, {x}, {y}, {w}, {h}, {len(data)}}},")
    data += px
out.append("static const snapshot_glyph snapshot_glyphs[95] = {")
out += rows
out.append("};")
out.append("")
out.append(f"static const uint8_t snapshot_glyph_data[{len(data)}] = {{")
for i in range(0, len(data), 24):
    out.append("    " + ",".join(str(b) for b in data[i:i+24]) + ",")
out.append("};")
out.append("")
out.append("#endif")
open("tools/snapshot_font.h", "w").write("\n".join(out) + "\n")
print(len(data), "bytes of glyph data, ascent", asc)
